### PR TITLE
split keys to array

### PR DESCRIPTION
**Pull request by darlanmendonca**
first, we need split keys to array, to do things with that, e.g. remove or keep keys in object

### CODE REVIEW

**Comment by darlanmendonca** [comment]
@hendriq check it pls

**Comment by henrique-voni** [comment]
Nice! Ok for me. 
TODO: Separate splitKeys in another module

**Comment by darlanmendonca** [comment]
Nice!!

I need fix CI before merge this PR

any idea?

**Comment by darlanmendonca** [comment]
"TODO: Separate splitKeys in another module"

I agree, after this task, lets move it to another module

**Pull request merged**
